"use strict";

const TOOL_MODULES = Object.freeze([
  require("./http-scan.js"),
  require("./read-http-audit.js"),
  require("./start-wave.js"),
  require("./import-http-traffic.js"),
  require("./public-intel.js"),
  require("./import-static-artifact.js"),
  require("./static-scan.js"),
  require("./record-finding.js"),
  require("./read-findings.js"),
  require("./list-findings.js"),
  require("./write-verification-round.js"),
  require("./read-verification-round.js"),
  require("./write-grade-verdict.js"),
  require("./read-grade-verdict.js"),
  require("./init-session.js"),
  require("./read-session-state.js"),
  require("./transition-phase.js"),
  require("./apply-wave-merge.js"),
  require("./write-handoff.js"),
  require("./write-wave-handoff.js"),
  require("./wave-handoff-status.js"),
  require("./merge-wave-handoffs.js"),
  require("./read-wave-handoffs.js"),
  require("./log-dead-ends.js"),
  require("./log-coverage.js"),
  require("./wave-status.js"),
  require("./temp-email.js"),
  require("./signup-detect.js"),
  require("./auth-store.js"),
  require("./list-auth-profiles.js"),
  require("./auto-signup.js"),
  require("./read-state-summary.js"),
  require("./read-hunter-brief.js"),
]);

module.exports = {
  TOOL_MODULES,
};
