"use strict";

const path = require("node:path");

const REPO_ROOT = path.resolve(__dirname, "../..");

function resolved(specifier) {
  const absolute = require.resolve(specifier);
  return Object.freeze({
    absolute,
    relative: path.relative(REPO_ROOT, absolute).split(path.sep).join("/"),
  });
}

// Stable identities for runtime modules inspected as files by tests. The only
// location spelling for each identity lives here, and Node resolves it to the
// authoritative absolute filename.
module.exports = Object.freeze({
  adjudicators: resolved("../../mcp/core/adjudicators.js"),
  approvalStore: resolved("../../mcp/core/approval-store.js"),
  auditReportParser: resolved("../../mcp/core/audit-report-parser.js"),
  beliefAuthority: resolved("../../mcp/core/belief/authority.js"),
  beliefExperimentLoop: resolved("../../mcp/core/belief/experiment-loop.js"),
  beliefFactorGraph: resolved("../../mcp/core/belief/factor-graph.js"),
  beliefFrontierFacts: resolved("../../mcp/core/belief/frontier-facts.js"),
  beliefModel: resolved("../../mcp/core/belief/model.js"),
  beliefResidual: resolved("../../mcp/core/belief/residual.js"),
  beliefWindow: resolved("../../mcp/core/belief/belief-window.js"),
  cellSchedulerPriority: resolved("../../mcp/core/belief/cell-scheduler-priority.js"),
  capabilityPacks: resolved("../../mcp/core/capability/capability-packs.js"),
  claimFreeze: resolved("../../mcp/core/claims/claim-freeze.js"),
  claims: resolved("../../mcp/core/claims/claims.js"),
  compositionLiveVerifier: resolved("../../mcp/core/differential/index.js"),
  compositionLiveVerifierStrategySource: resolved("../../mcp/core/differential/composition-live-verifier.js"),
  contractTarget: resolved("../../mcp/domains/blockchain/contract-target.js"),
  coverageClosure: resolved("../../mcp/core/frontier/coverage-closure.js"),
  cvss31: resolved("../../mcp/core/scoring/cvss31.js"),
  enforcementAttest: resolved("../../mcp/core/enforcement-attest.js"),
  executedEvidenceRegistry: resolved("../../mcp/core/executed-evidence-registry.js"),
  finalizeNode: resolved("../../mcp/tools/finalize-node.js"),
  findingVocabulary: resolved("../../mcp/core/constants/finding-vocabulary.js"),
  frictionSelection: resolved("../../mcp/core/friction-selection.js"),
  gradeVerdictStore: resolved("../../mcp/core/grade-verdict-store.js"),
  graphScheduler: resolved("../../mcp/core/waves/graph-scheduler.js"),
  httpRecords: resolved("../../mcp/core/io/http-records.js"),
  instrumentCapabilities: resolved("../../mcp/domains/physical/instrument-capabilities.js"),
  instrumentCapabilitiesChameleon: resolved("../../mcp/domains/physical/instrument-capabilities-chameleon.js"),
  instrumentBootstrapContract: resolved("../../mcp/domains/physical/instrument-bootstrap-contract.js"),
  instrumentBootstrapStore: resolved("../../mcp/domains/physical/instrument-bootstrap-store.js"),
  instrumentLeaseContract: resolved("../../mcp/domains/physical/instrument-lease-contract.js"),
  instrumentLeaseStore: resolved("../../mcp/domains/physical/instrument-lease-store.js"),
  instrumentProviderContract: resolved("../../mcp/domains/physical/instrument-provider-contract.js"),
  instrumentSafetySupervisor: resolved("../../mcp/domains/physical/instrument-safety-supervisor.js"),
  interventionCalculus: resolved("../../mcp/core/belief/intervention-calculus.js"),
  invariantRegistry: resolved("../../mcp/core/invariant-registry.js"),
  leadIntake: resolved("../../mcp/core/frontier/lead-intake.js"),
  leadPromotion: resolved("../../mcp/core/frontier/lead-promotion.js"),
  leadScoring: resolved("../../mcp/core/frontier/lead-scoring.js"),
  lifecycleGates: resolved("../../mcp/core/session/lifecycle-gates.js"),
  materializeProducerFloor: resolved("../../mcp/tools/materialize-producer-floor.js"),
  mechanismTemplateRegistry: resolved("../../mcp/core/mechanism-template-registry.js"),
  offensiveCaptureWriter: resolved("../../mcp/domains/web/offensive-capture-writer.js"),
  offensiveCorsProducer: resolved("../../mcp/domains/web/offensive-cors-producer.js"),
  offensiveIdorProducer: resolved("../../mcp/domains/web/offensive-idor-producer.js"),
  offensiveMassreadProducer: resolved("../../mcp/domains/web/offensive-massread-producer.js"),
  offensiveNucleiProducer: resolved("../../mcp/domains/web/offensive-nuclei-producer.js"),
  offensiveReflectProducer: resolved("../../mcp/domains/web/offensive-reflect-producer.js"),
  offensiveRunner: resolved("../../mcp/domains/web/offensive-runner.js"),
  offensiveSecondorderProducer: resolved("../../mcp/domains/web/offensive-secondorder-producer.js"),
  offensiveXssExecProducer: resolved("../../mcp/domains/web/offensive-xss-exec-producer.js"),
  oobCollector: resolved("../../mcp/domains/web/oob-collector.js"),
  paths: resolved("../../mcp/core/io/paths.js"),
  physicalAuthority: resolved("../../mcp/domains/physical/physical-authority.js"),
  physicalCampaignAnchor: resolved("../../mcp/domains/physical/physical-campaign-anchor.js"),
  physicalCampaignClosure: resolved("../../mcp/domains/physical/physical-campaign-closure.js"),
  physicalCampaignCoordinator: resolved("../../mcp/domains/physical/physical-campaign-coordinator.js"),
  physicalDispatchAuthority: resolved("../../mcp/domains/physical/physical-dispatch-authority.js"),
  physicalExperimentContract: resolved("../../mcp/domains/physical/physical-experiment-contract.js"),
  physicalInventoryCheckpoint: resolved("../../mcp/domains/physical/physical-inventory-checkpoint.js"),
  physicalLifecycleCapstone: resolved("../../mcp/domains/physical/physical-lifecycle-capstone.js"),
  physicalProviderAuthoring: resolved("../../mcp/domains/physical/physical-provider-authoring.js"),
  physicalQuantities: resolved("../../mcp/domains/physical/physical-quantities.js"),
  physicalResourceArbiter: resolved("../../mcp/domains/physical/physical-resource-arbiter.js"),
  physicalResourceGraphCoordinator: resolved("../../mcp/domains/physical/physical-resource-graph-coordinator.js"),
  physicalScope: resolved("../../mcp/domains/physical/physical-scope.js"),
  physicalSensitiveMaterial: resolved("../../mcp/core/physical-sensitive-material-contracts.js"),
  physicalSurfaceTransition: resolved("../../mcp/domains/physical/physical-surface-transition.js"),
  physicalTechniqueCompositionRoot: resolved("../../mcp/domains/physical/physical-technique-composition-root.js"),
  physicalTrustedClock: resolved("../../mcp/domains/physical/physical-trusted-clock.js"),
  physicalTrustedClockStore: resolved("../../mcp/domains/physical/physical-trusted-clock-store.js"),
  planePhysicalGateEvidence: resolved("../../mcp/domains/physical/plane-physical-gate-evidence.js"),
  planePhysicalReleaseContracts: resolved("../../mcp/domains/physical/plane-physical-release-contracts.js"),
  planePhysicalReleaseReadiness: resolved("../../mcp/domains/physical/plane-physical-release-readiness.js"),
  planePhysicalReleaseSnapshot: resolved("../../mcp/domains/physical/plane-physical-release-snapshot.js"),
  planeRegistry: resolved("../../mcp/core/dispatch/plane-registry.js"),
  queryInstrumentCapabilities: resolved("../../mcp/tools/physical/query-instrument-capabilities.js"),
  reachability: resolved("../../mcp/core/frontier/reachability.js"),
  reachabilityCeiling: resolved("../../mcp/core/frontier/reachability-ceiling.js"),
  recordCandidateClaim: resolved("../../mcp/tools/record-candidate-claim.js"),
  reportFinalize: resolved("../../mcp/core/report-finalize.js"),
  repoEnv: resolved("../../mcp/domains/repo/repo-env.js"),
  repoTarget: resolved("../../mcp/domains/repo/repo-target.js"),
  roleModel: resolved("../../mcp/core/dispatch/role-model.js"),
  requestedEffects: resolved("../../mcp/core/requested-effects.js"),
  schedulerPreconditions: resolved("../../mcp/core/waves/scheduler-preconditions.js"),
  schedulerPriority: resolved("../../mcp/core/belief/scheduler-priority.js"),
  scAnchorRunner: resolved("../../mcp/domains/blockchain/smart-contracts/anchor-runner.js"),
  scAptosClient: resolved("../../mcp/domains/blockchain/smart-contracts/aptos-client.js"),
  scAptosRunner: resolved("../../mcp/domains/blockchain/smart-contracts/aptos-runner.js"),
  scCosmwasmClient: resolved("../../mcp/domains/blockchain/smart-contracts/cosmwasm-client.js"),
  scCosmwasmRunner: resolved("../../mcp/domains/blockchain/smart-contracts/cosmwasm-runner.js"),
  scEvmClient: resolved("../../mcp/domains/blockchain/smart-contracts/evm-client.js"),
  scEvmSource: resolved("../../mcp/domains/blockchain/smart-contracts/evm-source.js"),
  scFoundryRunner: resolved("../../mcp/domains/blockchain/smart-contracts/foundry-runner.js"),
  scHalmosRunner: resolved("../../mcp/domains/blockchain/smart-contracts/halmos-runner.js"),
  scHttpClient: resolved("../../mcp/domains/blockchain/smart-contracts/sc-http-client.js"),
  scJsonRpcTransport: resolved("../../mcp/domains/blockchain/smart-contracts/json-rpc-transport.js"),
  scSubstrateClient: resolved("../../mcp/domains/blockchain/smart-contracts/substrate-client.js"),
  scSubstrateRunner: resolved("../../mcp/domains/blockchain/smart-contracts/substrate-runner.js"),
  scSuiClient: resolved("../../mcp/domains/blockchain/smart-contracts/sui-client.js"),
  scSuiRunner: resolved("../../mcp/domains/blockchain/smart-contracts/sui-runner.js"),
  scSvmClient: resolved("../../mcp/domains/blockchain/smart-contracts/svm-client.js"),
  scope: resolved("../../mcp/core/scope.js"),
  sessionState: resolved("../../mcp/core/session/session-state.js"),
  sessionAuthority: resolved("../../mcp/core/session/session-authority.js"),
  sessionStateContracts: resolved("../../mcp/core/session/session-state-contracts.js"),
  sessionStateStore: resolved("../../mcp/core/session/session-state-store.js"),
  stigmergicConsumers: resolved("../../mcp/core/stigmergic-consumers.js"),
  surfaceGraph: resolved("../../mcp/core/frontier/surface-graph.js"),
  surfaceLeads: resolved("../../mcp/core/frontier/surface-leads.js"),
  targetClassPackDerivation: resolved("../../mcp/core/capability/target-class-pack-derivation.js"),
  techniquePackDerivation: resolved("../../mcp/core/capability/capability-pack-derivation.js"),
  toolRegistry: resolved("../../mcp/tools/tool-registry.js"),
  transport: resolved("../../mcp/core/io/transport.js"),
  validation: resolved("../../mcp/core/io/validation.js"),
  verificationContracts: resolved("../../mcp/core/verification/verification-contracts.js"),
  waveAssignmentStore: resolved("../../mcp/core/waves/wave-assignment-store.js"),
  waveMergeSettler: resolved("../../mcp/core/waves/wave-merge-settler.js"),
  wavePlanner: resolved("../../mcp/core/waves/wave-planner.js"),
  waveScheduler: resolved("../../mcp/core/waves/wave-scheduler.js"),
  webPlane: resolved("../../mcp/domains/web/plane.js"),
  amendReport: resolved("../../mcp/tools/amend-report.js"),
  composeReport: resolved("../../mcp/tools/compose-report.js"),
  finalizeReport: resolved("../../mcp/tools/finalize-report.js"),
  initContractSession: resolved("../../mcp/tools/blockchain/init-contract-session.js"),
  initPhysicalSession: resolved("../../mcp/tools/physical/init-physical-session.js"),
  initRepoSession: resolved("../../mcp/tools/repo/init-repo-session.js"),
  initSession: resolved("../../mcp/tools/init-session.js"),
  setFrictionScanners: resolved("../../mcp/tools/set-friction-scanners.js"),
  writeBase: resolved("../../mcp/tools/_write-base.js"),
  writeChainAttempt: resolved("../../mcp/tools/write-chain-attempt.js"),
  writeChainRollup: resolved("../../mcp/tools/write-chain-rollup.js"),
  writeEvidencePacks: resolved("../../mcp/tools/write-evidence-packs.js"),
  writeGradeVerdict: resolved("../../mcp/tools/write-grade-verdict.js"),
  writeProofBundle: resolved("../../mcp/tools/write-proof-bundle.js"),
  writeVerificationRound: resolved("../../mcp/tools/write-verification-round.js"),
  writeWaveHandoff: resolved("../../mcp/tools/write-wave-handoff.js"),
});
